
[env]
TERM = "xterm-256color"

[font]
size = 17
normal.family = "JetBrainsMono Nerd Font"
normal.style= "Regular"

[window]
decorations = "Transparent"
opacity = 0.93
padding.x = 13
padding.y = 13
dimensions.columns = 120
dimensions.lines = 43
position.x = 550
position.y = 200

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[colors]
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'
