{ config, inputs, pkgs, lib, hostname, ... }:
{
  home.stateVersion = "24.11";
  home.homeDirectory = "/Users/hugoruiz";

  programs.home-manager.enable = true;

  # ===== PACKAGES =====
  home.packages = with pkgs; [
    devenv
  ];

  # ===== SOPS SECRET MANAGEMENT =====
  # NOTE: We use 'sops -d' directly in shell configs instead of sops-nix
  # to avoid storing decrypted secrets on disk.
  #
  # Secrets are stored encrypted in: ~/.config/nixos/secrets/
  # Age key location: ~/Library/Application Support/sops/age/keys.txt
  #
  # Usage in shells:
  #   Fish:    set -gx API_KEY (sops -d ~/.config/nixos/secrets/file.yaml | yq '.KEY')
  #   Nushell: $env.API_KEY = (sops -d ~/.config/nixos/secrets/file.yaml | from yaml | get KEY)
  #   Zsh:     export API_KEY=$(sops -d ~/.config/nixos/secrets/file.yaml | yq '.KEY')

  # ===== DECLARATIVE SHELL INTEGRATIONS =====

  # Zoxide - smart cd
  # NOTE: All shell integrations are disabled because we manage them manually
  # via home.activation.generateShellIntegrations which creates ~/.zoxide.{fish,nu,zsh,bash}
  programs.zoxide = {
    enable = true;
    enableFishIntegration = false;
    enableZshIntegration = false;
    enableNushellIntegration = false;
    enableBashIntegration = false;
  };

  # Atuin - shell history search
  # NOTE: All shell integrations are disabled because we manage them manually
  # via home.activation.generateShellIntegrations which creates ~/.atuin.{fish,nu,zsh,bash}
  programs.atuin = {
    enable = true;
    enableFishIntegration = false;
    enableZshIntegration = false;
    enableNushellIntegration = false;
    enableBashIntegration = false;
  };

  # Starship - cross-shell prompt
  # NOTE: All shell integrations are disabled because we manage them manually
  # via home.activation.generateShellIntegrations which creates ~/.starship.{fish,nu,zsh,bash}
  # User configuration lives in ~/.config/starship.toml (editable without rebuild)
  programs.starship = {
    enable = true;
    enableFishIntegration = false;
    enableZshIntegration = false;
    enableNushellIntegration = false;
    enableBashIntegration = false;
  };

  # Fish shell - User manages config manually in ~/.config/fish/
  # Philosophy: Nix installs → User configures in ~/.config
  programs.fish.enable = false;

  # Zsh configuration - managed manually in ~/.zshrc
  # Nix only installs zsh, user configures in ~/.config per philosophy
  programs.zsh = {
    enable = false;  # Disabled: user manages shell config manually
  };

  # Nushell configuration
  # NOTE: We only enable programs.nushell for package installation and basic setup.
  # Config files are managed separately:
  #   - env.nu: Generated by xdg.configFile (see below) with SOPS secrets
  #   - config.nu: User-managed in ~/.config/nushell/config.nu
  #   - Integrations: Generated by home.activation.generateShellIntegrations
  programs.nushell = {
    enable = true;
  };

  # Explicitly generate nushell env.nu with SOPS secrets
  xdg.configFile."nushell/env.nu".text = ''
    # Configure PATH for Nix/Darwin
    $env.PATH = (
      $env.PATH
      | split row (char esep)
      | prepend /run/current-system/sw/bin
      | prepend $"($env.HOME)/.nix-profile/bin"
      | prepend /nix/var/nix/profiles/default/bin
      | prepend $"($env.HOME)/.local/bin"
      | prepend $"($env.HOME)/.npm-global/bin"
      | prepend $"($env.HOME)/.cargo/bin"
      | uniq
    )

    # Environment variables
    $env.EDITOR = "nvim"
    $env.TERMINAL = "alacritty"

    # SOPS configuration for CLI usage
    $env.SOPS_AGE_KEY_FILE = $"($env.HOME)/.local/share/sops/age/keys.txt"

    # Load secrets using sops -d (decrypts on-the-fly, no files on disk)
    # Use load-env to set multiple environment variables from decrypted YAML
    load-env {
      GEMINI_API_KEY: (sops -d --extract '["GEMINI_API_KEY"]' $"($env.HOME)/.config/nixos/secrets/gemini_api_key.yaml" | str trim)
      GOOGLE_API_KEY: (sops -d --extract '["GOOGLE_API_KEY"]' $"($env.HOME)/.config/nixos/secrets/google_api_key.yaml" | str trim)
    }
  '';

  # Fish environment configuration with SOPS secrets
  # NOTE: Following the "Exception Rule" - keeping Nix-managed files OUTSIDE ~/.config/
  # Fish will source this from user's ~/.config/fish/config.fish
  home.file.".fish_env".text = ''
    # Auto-generated by home-manager - DO NOT EDIT MANUALLY
    # SOPS-managed secrets and environment variables

    # Configure PATH for Nix/Darwin
    fish_add_path --prepend --global $HOME/.cargo/bin
    fish_add_path --prepend --global $HOME/.npm-global/bin
    fish_add_path --prepend --global $HOME/.local/bin
    fish_add_path --prepend --global /nix/var/nix/profiles/default/bin
    fish_add_path --prepend --global $HOME/.nix-profile/bin
    fish_add_path --prepend --global /run/current-system/sw/bin

    # Environment variables
    set -gx EDITOR nvim
    set -gx TERMINAL alacritty

    # SOPS configuration for CLI usage
    set -gx SOPS_AGE_KEY_FILE "$HOME/.local/share/sops/age/keys.txt"

    # Load secrets using sops -d (decrypts on-the-fly, no files on disk)
    set -gx GEMINI_API_KEY (sops -d "$HOME/.config/nixos/secrets/gemini_api_key.yaml" | yq '.GEMINI_API_KEY' | string trim)
    set -gx GOOGLE_API_KEY (sops -d "$HOME/.config/nixos/secrets/google_api_key.yaml" | yq '.GOOGLE_API_KEY' | string trim)
  '';

  # ===== SESSION CONFIGURATION =====

  home.sessionVariables = {
    EDITOR = "nvim";
    TERMINAL = "alacritty";
  };

  home.sessionPath = [
    "${config.home.homeDirectory}/.local/bin"
    "${config.home.homeDirectory}/.npm-global/bin"
  ];

  home.file.".hushlogin".text = "";

  # Zsh environment and secrets - source this from your manual ~/.zshrc with: source ~/.zshrc.secrets
  home.file.".zshrc.secrets".text = ''
    # Auto-generated by home-manager - DO NOT EDIT MANUALLY
    # SOPS-managed secrets and environment variables

    # Configure PATH for Nix/Darwin
    export PATH="$HOME/.cargo/bin:$HOME/.npm-global/bin:$HOME/.local/bin:/nix/var/nix/profiles/default/bin:$HOME/.nix-profile/bin:/run/current-system/sw/bin:$PATH"

    # Environment variables
    export EDITOR=nvim
    export TERMINAL=alacritty

    # SOPS configuration for CLI usage
    export SOPS_AGE_KEY_FILE="$HOME/.local/share/sops/age/keys.txt"

    # Load secrets using sops -d (decrypts on-the-fly, no files on disk)
    export GEMINI_API_KEY="$(sops -d "$HOME/.config/nixos/secrets/gemini_api_key.yaml" | yq '.GEMINI_API_KEY' | tr -d '\n')"
    export GOOGLE_API_KEY="$(sops -d "$HOME/.config/nixos/secrets/google_api_key.yaml" | yq '.GOOGLE_API_KEY' | tr -d '\n')"
  '';

  # ===== DEVENV + DIRENV INTEGRATION =====
  # Nix-managed exception: devenv generates direnvrc, must stay in sync with installed version
  home.activation.devenvDirenvrc = lib.hm.dag.entryAfter ["writeBoundary"] ''
    DIRENV_CONFIG_DIR="$HOME/.config/direnv"
    $DRY_RUN_CMD mkdir -p "$DIRENV_CONFIG_DIR"
    $DRY_RUN_CMD ${pkgs.devenv}/bin/devenv direnvrc > "$DIRENV_CONFIG_DIR/direnvrc"
    echo "✅ direnvrc generated from devenv ${pkgs.devenv.version}"
  '';

  # ===== HAMMERSPOON SYMLINK =====

  home.activation.hammerspoon = lib.hm.dag.entryAfter ["writeBoundary"] ''
    # Create Hammerspoon symlink from ~/.config/hammerspoon to ~/.hammerspoon
    CONFIG_DIR="$HOME/.config/hammerspoon"
    HAMMERSPOON_DIR="$HOME/.hammerspoon"

    # Backup existing directory if it's not a symlink
    if [ -d "$HAMMERSPOON_DIR" ] && [ ! -L "$HAMMERSPOON_DIR" ]; then
      $DRY_RUN_CMD mv "$HAMMERSPOON_DIR" "$HAMMERSPOON_DIR.backup.$(date +%Y%m%d_%H%M%S)"
      echo "🔨 Backed up existing Hammerspoon config"
    fi

    # Remove old symlink if it exists and points to wrong location
    if [ -L "$HAMMERSPOON_DIR" ] && [ "$(readlink "$HAMMERSPOON_DIR")" != "$CONFIG_DIR" ]; then
      $DRY_RUN_CMD rm "$HAMMERSPOON_DIR"
      echo "🔨 Removed old Hammerspoon symlink"
    fi

    # Create symlink if it doesn't exist
    if [ ! -e "$HAMMERSPOON_DIR" ]; then
      $DRY_RUN_CMD ln -sf "$CONFIG_DIR" "$HAMMERSPOON_DIR"
      echo "✅ Hammerspoon symlink created: $HAMMERSPOON_DIR -> $CONFIG_DIR"
    else
      echo "✅ Hammerspoon symlink already exists"
    fi
  '';

  # ===== CLAUDE CODE INSTALLATION =====

  home.activation.installClaude = lib.hm.dag.entryAfter ["writeBoundary"] ''
    echo "🤖 Checking Claude Code installation..."

    if ! command -v claude &> /dev/null; then
      echo "📥 Installing Claude Code..."
      # Export PATH with nix tools for the install script
      export PATH="${pkgs.curl}/bin:${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.gnugrep}/bin:${pkgs.gnused}/bin:${pkgs.gnutar}/bin:${pkgs.gzip}/bin:${pkgs.unzip}/bin:${pkgs.perl}/bin:$PATH"
      $DRY_RUN_CMD ${pkgs.curl}/bin/curl -fsSL https://claude.ai/install.sh | ${pkgs.bash}/bin/bash
      echo "✅ Claude Code installed successfully"
    else
      CLAUDE_VERSION=$(claude --version 2>/dev/null || echo "unknown")
      echo "✅ Claude Code already installed ($CLAUDE_VERSION)"
    fi
  '';

  # ===== OPENCODE INSTALLATION =====

  home.activation.installOpencode = lib.hm.dag.entryAfter ["writeBoundary"] ''
    echo "🔓 Checking Opencode installation..."

    if ! command -v opencode &> /dev/null; then
      echo "📥 Installing Opencode..."
      # Export PATH with nix tools for the install script
      export PATH="${pkgs.curl}/bin:${pkgs.bash}/bin:${pkgs.coreutils}/bin:${pkgs.gnugrep}/bin:${pkgs.gnused}/bin:${pkgs.gnutar}/bin:${pkgs.gzip}/bin:${pkgs.unzip}/bin:${pkgs.perl}/bin:$PATH"
      $DRY_RUN_CMD ${pkgs.curl}/bin/curl -fsSL https://opencode.ai/install | ${pkgs.bash}/bin/bash
      echo "✅ Opencode installed successfully"
    else
      OPENCODE_VERSION=$(opencode --version 2>/dev/null || echo "unknown")
      echo "✅ Opencode already installed ($OPENCODE_VERSION)"
    fi
  '';

  # ===== KARABINER-ELEMENTS CONFIG =====

  home.activation.karabiner = lib.hm.dag.entryAfter ["writeBoundary"] ''
    # Ensure Karabiner config directory exists
    KARABINER_CONFIG_DIR="$HOME/.config/karabiner"

    # Create directory structure if it doesn't exist
    if [ ! -d "$KARABINER_CONFIG_DIR" ]; then
      $DRY_RUN_CMD mkdir -p "$KARABINER_CONFIG_DIR/assets/complex_modifications"
      echo "⌨️  Created Karabiner config directory"
    fi

    # Verify config file exists
    if [ -f "$KARABINER_CONFIG_DIR/karabiner.json" ]; then
      echo "✅ Karabiner config ready: $KARABINER_CONFIG_DIR/karabiner.json"
    else
      echo "⚠️  Karabiner config not found. Please create ~/.config/karabiner/karabiner.json"
    fi
  '';

  # ===== LAUNCHD AGENTS =====

  launchd.agents.xdg-config = {
    enable = true;
    config = {
      ProgramArguments = [
        "/bin/sh"
        "-c"
        "/bin/launchctl setenv XDG_CONFIG_HOME $HOME/.config"
      ];
      RunAtLoad = true;
    };
  };

  launchd.agents.hammerspoon = {
    enable = true;
    config = {
      ProgramArguments = [
        "/Applications/Hammerspoon.app/Contents/MacOS/Hammerspoon"
      ];
      RunAtLoad = true;
      KeepAlive = false;
      StandardOutPath = "/tmp/hammerspoon.out.log";
      StandardErrorPath = "/tmp/hammerspoon.err.log";
    };
  };

  launchd.agents.karabiner = {
    enable = true;
    config = {
      ProgramArguments = [
        "/Applications/Karabiner-Elements.app/Contents/MacOS/Karabiner-Elements"
      ];
      RunAtLoad = true;
      KeepAlive = false;
      StandardOutPath = "/tmp/karabiner.out.log";
      StandardErrorPath = "/tmp/karabiner.err.log";
    };
  };

  # launchd.agents.sketchybar = {
  #   enable = true;
  #   config = {
  #     ProgramArguments = [
  #       "${pkgs.sketchybar}/bin/sketchybar"
  #     ];
  #     KeepAlive = true;
  #     RunAtLoad = true;
  #     StandardOutPath = "/tmp/sketchybar.out.log";
  #     StandardErrorPath = "/tmp/sketchybar.err.log";
  #     EnvironmentVariables = {
  #       PATH = "/run/current-system/sw/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";
  #     };
  #   };
  # };

  # ===== BASH CONFIGURATION =====
  # Bash is configured declaratively for full integration
  programs.bash = {
    enable = true;
    shellAliases = {
      cldy = "claude --dangerously-skip-permissions";
    };
    initExtra = ''
      # Load shell integration files generated by activation scripts
      [ -f ~/.zoxide.bash ] && source ~/.zoxide.bash
      [ -f ~/.atuin.bash ] && source ~/.atuin.bash
      [ -f ~/.starship.bash ] && source ~/.starship.bash
      [ -f ~/.yazi.bash ] && source ~/.yazi.bash
    '';
  };

  # ===== OUT-OF-THE-BOX SHELL INTEGRATION =====
  # This activation script ensures that all shells work immediately after installation
  # Philosophy: "Nix installs → User configures" maintained by generating auxiliary files
  # that users source in their configs, rather than overwriting user configs

  home.activation.generateShellIntegrations = lib.hm.dag.entryAfter ["writeBoundary"] ''
    echo ""
    echo "🐚 ================================================"
    echo "🐚 Generando integraciones de shell out-of-the-box"
    echo "🐚 ================================================"
    echo ""

    # ===== STEP 1: Generate integration files =====
    echo "📦 Paso 1/4: Generando archivos de integración..."
    echo ""

    # Zoxide integration files
    if [ -x "${pkgs.zoxide}/bin/zoxide" ]; then
      $DRY_RUN_CMD ${pkgs.zoxide}/bin/zoxide init fish > $HOME/.zoxide.fish 2>/dev/null && echo "  ✅ .zoxide.fish"
      $DRY_RUN_CMD ${pkgs.zoxide}/bin/zoxide init nushell > $HOME/.zoxide.nu 2>/dev/null && echo "  ✅ .zoxide.nu"
      $DRY_RUN_CMD ${pkgs.zoxide}/bin/zoxide init zsh > $HOME/.zoxide.zsh 2>/dev/null && echo "  ✅ .zoxide.zsh"
      $DRY_RUN_CMD ${pkgs.zoxide}/bin/zoxide init bash > $HOME/.zoxide.bash 2>/dev/null && echo "  ✅ .zoxide.bash"
    else
      echo "  ⚠️  zoxide no encontrado"
    fi

    # Atuin integration files
    if [ -x "${pkgs.atuin}/bin/atuin" ]; then
      $DRY_RUN_CMD mkdir -p $HOME/.local/share/atuin
      $DRY_RUN_CMD ${pkgs.atuin}/bin/atuin init fish 2>/dev/null | sed 's/bind \(.*\)-k up/bind \1up/' > $HOME/.atuin.fish && echo "  ✅ .atuin.fish (patched for Fish 4.x)"
      $DRY_RUN_CMD ${pkgs.atuin}/bin/atuin init nu --disable-up-arrow > $HOME/.local/share/atuin/init.nu 2>/dev/null && echo "  ✅ .local/share/atuin/init.nu"
      $DRY_RUN_CMD ${pkgs.atuin}/bin/atuin init zsh > $HOME/.atuin.zsh 2>/dev/null && echo "  ✅ .atuin.zsh"
      $DRY_RUN_CMD ${pkgs.atuin}/bin/atuin init bash > $HOME/.atuin.bash 2>/dev/null && echo "  ✅ .atuin.bash"
    else
      echo "  ⚠️  atuin no encontrado"
    fi

    # Direnv integration files (hook for auto-activating devenv on cd)
    if command -v direnv >/dev/null 2>&1; then
      $DRY_RUN_CMD direnv hook fish > $HOME/.direnv.fish 2>/dev/null && echo "  ✅ .direnv.fish"
      $DRY_RUN_CMD direnv hook zsh > $HOME/.direnv.zsh 2>/dev/null && echo "  ✅ .direnv.zsh"
      $DRY_RUN_CMD direnv hook bash > $HOME/.direnv.bash 2>/dev/null && echo "  ✅ .direnv.bash"
    else
      echo "  ⚠️  direnv no encontrado"
    fi

    # Starship integration files
    if [ -x "${pkgs.starship}/bin/starship" ]; then
      $DRY_RUN_CMD ${pkgs.starship}/bin/starship init fish > $HOME/.starship.fish 2>/dev/null && echo "  ✅ .starship.fish"
      $DRY_RUN_CMD ${pkgs.starship}/bin/starship init nu > $HOME/.starship.nu 2>/dev/null && echo "  ✅ .starship.nu"
      $DRY_RUN_CMD ${pkgs.starship}/bin/starship init zsh > $HOME/.starship.zsh 2>/dev/null && echo "  ✅ .starship.zsh"
      $DRY_RUN_CMD ${pkgs.starship}/bin/starship init bash > $HOME/.starship.bash 2>/dev/null && echo "  ✅ .starship.bash"
    else
      echo "  ⚠️  starship no encontrado"
    fi

    # Yazi wrapper functions
    $DRY_RUN_CMD cat > $HOME/.yazi.fish << 'EOF_YAZI_FISH'
# Yazi wrapper - cd to last directory on exit
function y
    set tmp (mktemp -t "yazi-cwd.XXXXXX")
    yazi $argv --cwd-file="$tmp"
    if read -z cwd <"$tmp"; and test -n "$cwd"; and test "$cwd" != "$PWD"
        builtin cd -- "$cwd"
    end
    rm -f -- "$tmp"
end
EOF_YAZI_FISH
    echo "  ✅ .yazi.fish"

    $DRY_RUN_CMD cat > $HOME/.yazi.nu << 'EOF_YAZI_NU'
# Yazi wrapper - cd to last directory on exit
def --env y [...args] {
    let tmp = (mktemp -t "yazi-cwd.XXXXXX")
    yazi ...$args --cwd-file $tmp
    let cwd = (open $tmp)
    if $cwd != "" and $cwd != $env.PWD {
        cd $cwd
    }
    rm -fp $tmp
}
EOF_YAZI_NU
    echo "  ✅ .yazi.nu"

    $DRY_RUN_CMD cat > $HOME/.yazi.bash << 'EOF_YAZI_BASH'
# Yazi wrapper - cd to last directory on exit
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d "" cwd < "$tmp"
    test -n "$cwd" && test "$cwd" != "$PWD" && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}
EOF_YAZI_BASH
    echo "  ✅ .yazi.bash"

    $DRY_RUN_CMD cat > $HOME/.yazi.zsh << 'EOF_YAZI_ZSH'
# Yazi wrapper - cd to last directory on exit
function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d "" cwd < "$tmp"
    test -n "$cwd" && test "$cwd" != "$PWD" && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}
EOF_YAZI_ZSH
    echo "  ✅ .yazi.zsh"

    # cldy alias files
    $DRY_RUN_CMD cat > $HOME/.cldy.fish << 'EOF_CLDY_FISH'
# Claude skip permissions alias
alias cldy="claude --dangerously-skip-permissions"
EOF_CLDY_FISH
    echo "  ✅ .cldy.fish"

    $DRY_RUN_CMD cat > $HOME/.cldy.nu << 'EOF_CLDY_NU'
# Claude skip permissions alias
alias cldy = claude --dangerously-skip-permissions
EOF_CLDY_NU
    echo "  ✅ .cldy.nu"

    echo ""

    # ===== STEP 2: Create minimal configs if they don't exist =====
    echo "📝 Paso 2/4: Verificando configs de shells..."
    echo ""

    # Fish config
    if [ ! -f "$HOME/.config/fish/config.fish" ]; then
      $DRY_RUN_CMD mkdir -p "$HOME/.config/fish"
      $DRY_RUN_CMD cat > "$HOME/.config/fish/config.fish" << 'EOF_FISH_CONFIG'
# ~/.config/fish/config.fish
# Manual configuration - User editable
# Generated by Nix home-manager on first install

# Nix-Managed Environment (load FIRST)
source ~/.fish_env

# Shell integrations (auto-generated by Nix)
source ~/.zoxide.fish
source ~/.atuin.fish
source ~/.starship.fish
source ~/.yazi.fish
source ~/.cldy.fish

# Add your custom configuration below this line
# ============================================

EOF_FISH_CONFIG
      echo "  ✅ Creado ~/.config/fish/config.fish (nuevo)"
    else
      echo "  ℹ️  ~/.config/fish/config.fish ya existe (no modificado)"
    fi

    # Nushell config.nu
    if [ ! -f "$HOME/.config/nushell/config.nu" ]; then
      $DRY_RUN_CMD mkdir -p "$HOME/.config/nushell"
      $DRY_RUN_CMD cat > "$HOME/.config/nushell/config.nu" << 'EOF_NU_CONFIG'
# ~/.config/nushell/config.nu
# Manual configuration - User editable
# Generated by Nix home-manager on first install

# Shell integrations (auto-generated by Nix)
source ~/.zoxide.nu
source ~/.local/share/atuin/init.nu
source ~/.starship.nu
source ~/.yazi.nu
source ~/.cldy.nu

# Add your custom configuration below this line
# ============================================

EOF_NU_CONFIG
      echo "  ✅ Creado ~/.config/nushell/config.nu (nuevo)"
    else
      echo "  ℹ️  ~/.config/nushell/config.nu ya existe (no modificado)"
    fi

    # Nushell env.nu is managed by xdg.configFile in home.nix
    echo "  ✅ Nushell env.nu → Managed by xdg.configFile (includes secrets)"

    # Zsh config
    if [ ! -f "$HOME/.zshrc" ]; then
      $DRY_RUN_CMD cat > "$HOME/.zshrc" << 'EOF_ZSH_CONFIG'
# ~/.zshrc
# Manual configuration - User editable
# Generated by Nix home-manager on first install

# Load Nix-managed environment and secrets FIRST
[ -f ~/.zshrc.secrets ] && source ~/.zshrc.secrets

# Shell integrations (auto-generated by Nix)
[ -f ~/.zoxide.zsh ] && source ~/.zoxide.zsh
[ -f ~/.atuin.zsh ] && source ~/.atuin.zsh
[ -f ~/.starship.zsh ] && source ~/.starship.zsh
[ -f ~/.yazi.zsh ] && source ~/.yazi.zsh

# Alias
alias cldy="claude --dangerously-skip-permissions"

# Add your custom configuration below this line
# ============================================

EOF_ZSH_CONFIG
      echo "  ✅ Creado ~/.zshrc (nuevo)"
    else
      echo "  ℹ️  ~/.zshrc ya existe (no modificado)"
    fi

    echo ""

    # ===== STEP 3: Auto-source in existing configs (idempotent) =====
    echo "🔗 Paso 3/4: Verificando sourceo automático..."
    echo ""

    # Fish - add sources if not present
    if [ -f "$HOME/.config/fish/config.fish" ]; then
      for file in fish_env zoxide.fish atuin.fish starship.fish yazi.fish cldy.fish direnv.fish; do
        if ! grep -q "source ~/.$file" "$HOME/.config/fish/config.fish" 2>/dev/null; then
          $DRY_RUN_CMD echo "source ~/.$file" >> "$HOME/.config/fish/config.fish"
          echo "  ✅ Fish: Agregado source ~/.$file"
        fi
      done
    fi

    # Nushell - add sources if not present
    if [ -f "$HOME/.config/nushell/config.nu" ]; then
      if ! grep -q "source ~/.zoxide.nu" "$HOME/.config/nushell/config.nu" 2>/dev/null; then
        $DRY_RUN_CMD echo "source ~/.zoxide.nu" >> "$HOME/.config/nushell/config.nu"
        echo "  ✅ Nushell: Agregado source ~/.zoxide.nu"
      fi
      if ! grep -q "source ~/.local/share/atuin/init.nu" "$HOME/.config/nushell/config.nu" 2>/dev/null; then
        $DRY_RUN_CMD echo "source ~/.local/share/atuin/init.nu" >> "$HOME/.config/nushell/config.nu"
        echo "  ✅ Nushell: Agregado source ~/.local/share/atuin/init.nu"
      fi
      if ! grep -q "source ~/.starship.nu" "$HOME/.config/nushell/config.nu" 2>/dev/null; then
        $DRY_RUN_CMD echo "source ~/.starship.nu" >> "$HOME/.config/nushell/config.nu"
        echo "  ✅ Nushell: Agregado source ~/.starship.nu"
      fi
      if ! grep -q "source ~/.yazi.nu" "$HOME/.config/nushell/config.nu" 2>/dev/null; then
        $DRY_RUN_CMD echo "source ~/.yazi.nu" >> "$HOME/.config/nushell/config.nu"
        echo "  ✅ Nushell: Agregado source ~/.yazi.nu"
      fi
      if ! grep -q "source ~/.cldy.nu" "$HOME/.config/nushell/config.nu" 2>/dev/null; then
        $DRY_RUN_CMD echo "source ~/.cldy.nu" >> "$HOME/.config/nushell/config.nu"
        echo "  ✅ Nushell: Agregado source ~/.cldy.nu"
      fi
    fi

    # Zsh - add sources if not present
    if [ -f "$HOME/.zshrc" ]; then
      for integration in zoxide atuin starship yazi direnv; do
        if ! grep -q "source ~/.$integration.zsh" "$HOME/.zshrc" 2>/dev/null; then
          # Find the right place to insert (after PATH but before custom config)
          if grep -q "# Add your custom configuration" "$HOME/.zshrc"; then
            $DRY_RUN_CMD sed -i.bak "/# Add your custom configuration/i [ -f ~/.$integration.zsh ] && source ~/.$integration.zsh" "$HOME/.zshrc"
            $DRY_RUN_CMD rm -f "$HOME/.zshrc.bak"
          else
            $DRY_RUN_CMD echo "[ -f ~/.$integration.zsh ] && source ~/.$integration.zsh" >> "$HOME/.zshrc"
          fi
          echo "  ✅ Zsh: Agregado source ~/.$integration.zsh"
        fi
      done
    fi

    echo ""

    # ===== STEP 4: Summary =====
    echo "📊 Paso 4/4: Resumen de configuración"
    echo ""
    echo "  ✅ Fish    → ~/.config/fish/config.fish (user-editable)"
    echo "  ✅ Nushell → ~/.config/nushell/config.nu + env.nu"
    echo "  ✅ Zsh     → ~/.zshrc (user-editable)"
    echo "  ✅ Bash    → Configurado vía programs.bash"
    echo ""
    echo "🎉 Out-of-the-box shell integration completa!"
    echo ""
    echo "💡 Todas las shells ahora tienen:"
    echo "   - Atuin (Ctrl+R para búsqueda de historial)"
    echo "   - Zoxide (comando 'z' para navegación inteligente)"
    echo "   - Yazi (comando 'y' wrapper con cd al salir)"
    echo "   - Alias 'cldy' (Claude skip permissions)"
    echo "   - Direnv (auto-activación de devenv al entrar en proyecto)"
    echo ""
    echo "📝 Filosofía mantenida: 'Nix installs → User configures'"
    echo "   Los archivos en ~/.config/ son editables por el usuario."
    echo "   Nix solo genera archivos auxiliares (~/.zoxide.fish, etc.)"
    echo ""
    echo "🐚 ================================================"
    echo ""
  '';
}
