# Portable config - works on Nix, NixOS, and Arch Linux

# 1. Environment (portable, platform-aware)
source ~/.config/shell/env.fish

# 2. Tracked integrations (committed to git)
source ~/.config/shell/integrations/zoxide.fish
source ~/.config/shell/integrations/atuin.fish
source ~/.config/shell/integrations/yazi.fish
source ~/.config/shell/integrations/cldy.fish
command -q mise; and mise activate fish | source

# 3. Cached integrations (generated by bootstrap.sh, contain system paths)
test -f ~/.cache/shell/starship.fish; and source ~/.cache/shell/starship.fish
test -f ~/.cache/shell/direnv.fish; and source ~/.cache/shell/direnv.fish
