# Portable config - works on Nix, NixOS, and Arch Linux

# 1. Environment (portable, platform-aware)
source ~/.config/shell/env.fish

# 2. Tracked integrations (committed to git)
source ~/.config/shell/integrations/zoxide.fish
source ~/.config/shell/integrations/atuin.fish
source ~/.config/shell/integrations/yazi.fish
source ~/.config/shell/integrations/tv.fish
source ~/.config/shell/integrations/cldy.fish
command -q mise; and mise activate fish | source

# 3. Cached integrations (generated by bootstrap.sh, contain system paths)
test -f ~/.cache/shell/starship.fish; and source ~/.cache/shell/starship.fish


# Google Cloud SDK
if test -d "$HOME/google-cloud-sdk/bin"
    fish_add_path --prepend --global $HOME/google-cloud-sdk/bin
end

function add-secret
    if test (count $argv) -lt 2
        echo "Usage: add-secret VAR_NAME value" >&2; return 1
    end
    ~/.config/shell/scripts/add-secret $argv[1] $argv[2]; and set -gx $argv[1] $argv[2]
end
